on:
  push:
    branches:
      - master
name: Build and deploy on push
jobs:
  build:
    name: jomaro/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: jomaro/zola-deploy-action
      uses: jomaro/zola-deploy-action@0.16.1
      env:
        TOKEN: ${{ secrets.TOKEN }}